// User Actions
export const USER_REQUEST_INITIATED = 'USER_REQUEST_INITIATED';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAIL = 'USER_REQUEST_FAIL';

// Check Authentication
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
